   CLADE : "sharks"
   SPEC_NAME : "NarBan"
   REF_NAME : "GCA_036971175.1"
   ALT_NAME : "GCA_036971445.1"
   TODAY_DATE : "20250411"
   CHROM_START_CHR : "CM"
   CHROM_LIST_FILE : "/rds/project/rds-p67MZilb2eQ/projects/VGP/heterozygosity/sharks/chrom_lists/NarBan_chroms.txt"
   WINDOW_INTERVAL : 500000
   WINDOW_LENGTH : 1000000
   NUM_AUT_CHROMOSOMES : 14
   NUM_ALL_CHR: 14
   ALL_CHROMOSOMES : 
      - CM072956.1
      - CM072957.1
      - CM072958.1
      - CM072959.1
      - CM072960.1
      - CM072961.1
      - CM072962.1
      - CM072963.1
      - CM072964.1
      - CM072965.1
      - CM072966.1
      - CM072967.1
      - CM072968.1
      - CM072969.1
   AUTOSOMAL_CHROMOSOMES:
      - CM072956.1
      - CM072957.1
      - CM072958.1
      - CM072959.1
      - CM072960.1
      - CM072961.1
      - CM072962.1
      - CM072963.1
      - CM072964.1
      - CM072965.1
      - CM072966.1
      - CM072967.1
      - CM072968.1
      - CM072969.1
   BOOTSTRAPPING_VALUES:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29